// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWZM0bZvWwB0Oxtw6ClaGwdPFeLlAF_8Q',
    appId: '1:964930079549:web:bf563ea5ff3e5734e2d354',
    messagingSenderId: '964930079549',
    projectId: 'regentsspace',
    authDomain: 'regentsspace.firebaseapp.com',
    storageBucket: 'regentsspace.firebasestorage.app',
    measurementId: 'G-JRLKC6EYYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnVKi3K2jZt-nTtwZYUmVPgZN-6R7_WTc',
    appId: '1:964930079549:android:d32a3b0112f77a91e2d354',
    messagingSenderId: '964930079549',
    projectId: 'regentsspace',
    storageBucket: 'regentsspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz6eQGvu4NFLPVGqEAkcLOP_Dbc8CMp-o',
    appId: '1:964930079549:ios:a7b2f6c9ab9cca3ae2d354',
    messagingSenderId: '964930079549',
    projectId: 'regentsspace',
    storageBucket: 'regentsspace.firebasestorage.app',
    iosBundleId: 'com.example.regentspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz6eQGvu4NFLPVGqEAkcLOP_Dbc8CMp-o',
    appId: '1:964930079549:ios:a7b2f6c9ab9cca3ae2d354',
    messagingSenderId: '964930079549',
    projectId: 'regentsspace',
    storageBucket: 'regentsspace.firebasestorage.app',
    iosBundleId: 'com.example.regentspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWZM0bZvWwB0Oxtw6ClaGwdPFeLlAF_8Q',
    appId: '1:964930079549:web:dfbc043f253a5b43e2d354',
    messagingSenderId: '964930079549',
    projectId: 'regentsspace',
    authDomain: 'regentsspace.firebaseapp.com',
    storageBucket: 'regentsspace.firebasestorage.app',
    measurementId: 'G-EXB8X8Q1QF',
  );
}
